### ISSUE TITLE
Would be nice to give instructions for the release build

### ISSUE THREAD

**Issue by TedSander** [dart-lang/angular_components_example#67]
The readme only has info on how to build/serve for DDC. Would be nice to give the documentation for how to release dart2js.

In particular DDC on this app crashes an iPad Pro chrome, and safari. Probably requires too much memory for the device.

**Comment by chalin** [comment]
FYI, we now have such guidance on the [tool > build_runner](https://webdev-dartlang-org-dev.firebaseapp.com/tools/build_runner) page of the 5-dev version of the webdev site.

cc @kwalrath

**Comment by nshahan** [comment]
The dart2js build was a bit convoluted for a little while because build_runner didn't support differed loading. I didn't think it was worth documenting the hoops I was jumping through. 

In the latest branch, I am updating to build_runner: 0.8.0 that has full support. At that point you can run 
`pub run build_runner serve web --config release` to serve a version compiled with dart2js. I'll update the README before it lands.

**Comment by TedSander** [comment]
SGTM yeah I did the same thing. Was running dart2js by hand on a release output. Pretty nasty stuff.
