### ISSUE TITLE
Example missing for `<reorder-list>` component

### ISSUE THREAD

**Issue by pslavers** [dart-lang/angular_components_example#90]
There is no example for `reorder-list` in `dart-langangular_components_example/example/`.

Thank you.

**Comment by nshahan** [comment]
I chose not to advertise that component in the examples because the support is limited. It doesn't work correctly in all browsers or on mobile. The component was included in the initial release so I left it in, but it probably was included too early.

If you are already using it do you have a specific question about the implementation?
